---
title: "Analyze Distances"
output:
  html_document:
    theme: united
    df_print: paged
    highlight: tango
    smart: false
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F, fig.width=10)
```

```{r}
library( dplyr )
library( tidyr )
library( pander )
library( geosphere )
library( ggplot2 )
library( forcats )
library( ggmap )
```

# Load Data

```{r, cache=T}
dist.npos <- readRDS( "data-prepped/ave-dist-officers-to-npo.rds" )
ave.dist <- readRDS( "data-prepped/ave-dist-btwn-officers.rds" )
dist <- readRDS( "data-prepped/officer-to-officer-dist.rds")
```


```{r, cache=T}
npos <- readRDS( "data-geo/NPOS-GEOCODES-COMPILED.rds" )
npos <- filter( npos, match == "Match" )
npos$EIN <- substr( npos$id, 9, 17 )
head( npos ) # %>% pander()

peeps <- readRDS( "data-geo/PEOPLE-GEOCODES-COMPILED.rds" )
peeps <- filter( peeps, match == "Match" )
head( peeps ) # %>% pander()
```


# Dist Function


### Dist between nonprofits and board members

```{r}
# Calculate distance in kilometers between two points
earth.dist <- function( long1, lat1, long2, lat2 )
{
rad <- pi/180
a1 <- lat1 * rad
a2 <- long1 * rad
b1 <- lat2 * rad
b2 <- long2 * rad
dlon <- b2 - a2
dlat <- b1 - a1
a <- (sin(dlat/2))^2 + cos(a1) * cos(b1) * (sin(dlon/2))^2
c <- 2 * atan2(sqrt(a), sqrt(1 - a))
R <- 6378.145
d <- R * c
miles <- d * 0.621371  # convert km to miles
return(miles)
}
```




# Descriptives

```{r}
ave.d <- ave.dist$ave.dist 

ad <- ave.dist[ ave.dist$ave.dist < 5 , ]
ggplot( ad, aes( x=ave.dist, fill="steelblue" ) ) +
  geom_density()

ad <- ave.dist[ ave.dist$ave.dist < 25 & ave.dist$ave.dist > 0, ]
hist( ad$ave.dist, breaks=100, col="gray", border="white",
      xlim=c(0,25) )
```

```{r}
# library( ggplot2 )
ave.d.npo <-
  dist.npos %>%
  group_by( id.npo ) %>%
  summarize( ave.dist.to.npo = mean( dist.to.npo ) ) %>%
  ungroup()

ave.d.np <- ave.d.npo$ave.dist.to.npo

ad <- ave.dist[ ave.dist$ave.dist < 5 , ]
ggplot( ad, aes( x=ave.dist, fill="steelblue" ) ) +
  geom_density()

mean( ave.d.np == 0 ) # 30% have distance of zero

mean( ave.d.np < 10 ) # 77% are within 10 miles


hist( ave.d.np[ ave.d.np < 10 & ave.d.np > 0  ], 
      breaks=100, col="gray", border="white" )
```


```{r, fig.width=5, fig.height=5}
groups <- cut( ave.d.np, breaks=seq( from=-0.5, to=25, by=0.5 ) )
tb <- table( groups ) / length( ave.d.np )
tb.cumul <- cumsum( tb )

plot( seq( from=0, to=25, by=0.5 ), tb.cumul, 
      type="b", pch=19, ylim=c(0,0.9), bty="n",
      ylab="Cumulative Prop. of Nonprofits", xlab="Miles", 
      main="Ave Distance of Nonprofit Officers to HQs" )
abline( h=seq(0.1,1,0.1), lty=2, col="gray" )
abline( v=seq(0,25,1), lty=2, col="gray" )
points( seq( from=0, to=25, by=0.5 ), tb.cumul, type="b", pch=19 )
```



```{r}
these <- as.numeric( c("003", "005", "007", "019", "051", "125", "129" ) )
pitt.npos <- npos[ npos$state_fips == 42 & npos$county_fips == 3 , ]
pitt.peeps <- peeps[ peeps$state_fips == 42 & peeps$county_fips == 3 , ]

# plot( pitt$lon, pitt$lat )
qmplot( lon, lat, data=pitt.npos, maptype="toner-lite", color=I("red") )

qmplot( lon, lat, data=pitt.peeps, maptype="toner-lite", color=I("steelblue") )
```








```{r}
pd <- dist.npos[ dist.npos$id.npo %in% unique( pitt.npos$id ) , ]

max.x <- max( c(pd$lon.npo) )
min.x <- min( c(pd$lon.npo) )
max.y <- max( c(pd$lat.npo) )
min.y <- min( c(pd$lat.npo) )

# distance in miles from furthest points
d.x <- earth.dist( long1=max.x, long2=min.x,lat1=40.66, lat2=40.66 )
d.y <- earth.dist( long1=-79.71, long2=-79.70, lat1=min.y, lat2=max.y )

# create a local board code for npos with board members in county only
pd <- 
  pd %>%
  group_by( id.npo ) %>%
  mutate( min.y.peeps = min( lat.peeps ),
          max.y.peeps = max( lat.peeps ),
          min.x.peeps = min( lon.peeps ),
          max.x.peeps = max( lon.peeps ) ) %>%
  mutate( LOCAL = min.y.peeps > min.y & max.y.peeps < max.y & 
                min.x.peeps > min.x & max.x.peeps < max.x ) %>%
  ungroup()


dd <- pd[ pd$LOCAL , ]
dd <- dd[ dd$id.npo %in% dd$id.npo[sample(1:nrow(dd),10)] , ]

```


```{r, eval=T}
dd2 <- 
structure(list(id.npo = c("ID-2015-272357477", "ID-2015-272357477", 
"ID-2015-272357477", "ID-2015-463279966", "ID-2015-463279966", 
"ID-2015-463279966", "ID-2015-471155801", "ID-2015-472085945", 
"ID-2015-472085945", "ID-2015-472085945", "ID-2015-472085945", 
"ID-2016-364841262", "ID-2016-421636657", "ID-2016-421636657", 
"ID-2016-421636657", "ID-2016-421636657", "ID-2016-421636657", 
"ID-2016-811470948", "ID-2016-811470948", "ID-2016-811470948", 
"ID-2016-811470948", "ID-2016-812329206", "ID-2016-812329206", 
"ID-2016-812329206", "ID-2016-812329206", "ID-2017-251350410", 
"ID-2017-251350410", "ID-2017-251350410", "ID-2017-251350410", 
"ID-2017-251350410", "ID-2017-821940719", "ID-2017-821940719", 
"ID-2017-821940719", "ID-2017-821940719"), lon.npo = c(-79.939644, 
-79.939644, -79.939644, -79.972496, -79.972496, -79.972496, -80.00842, 
-79.97723, -79.97723, -79.97723, -79.97723, -79.80957, -79.87476, 
-79.87476, -79.87476, -79.87476, -79.87476, -80.01211, -80.01211, 
-80.01211, -80.01211, -80.044914, -80.044914, -80.044914, -80.044914, 
-80.08372, -80.08372, -80.08372, -80.08372, -80.08372, -80.000595, 
-80.000595, -80.000595, -80.000595), lat.npo = c(40.46608, 40.46608, 
40.46608, 40.539185, 40.539185, 40.539185, 40.505516, 40.41782, 
40.41782, 40.41782, 40.41782, 40.342606, 40.457756, 40.457756, 
40.457756, 40.457756, 40.457756, 40.42181, 40.42181, 40.42181, 
40.42181, 40.336117, 40.336117, 40.336117, 40.336117, 40.510147, 
40.510147, 40.510147, 40.510147, 40.510147, 40.448425, 40.448425, 
40.448425, 40.448425), id.peeps = c("ID-2015-272357477-01", "ID-2015-272357477-03", 
"ID-2015-272357477-04", "ID-2015-463279966-01", "ID-2015-463279966-02", 
"ID-2015-463279966-03", "ID-2015-471155801-02", "ID-2015-472085945-01", 
"ID-2015-472085945-02", "ID-2015-472085945-03", "ID-2015-472085945-04", 
"ID-2016-364841262-01", "ID-2016-421636657-01", "ID-2016-421636657-02", 
"ID-2016-421636657-03", "ID-2016-421636657-04", "ID-2016-421636657-05", 
"ID-2016-811470948-01", "ID-2016-811470948-02", "ID-2016-811470948-03", 
"ID-2016-811470948-04", "ID-2016-812329206-01", "ID-2016-812329206-02", 
"ID-2016-812329206-03", "ID-2016-812329206-04", "ID-2017-251350410-01", 
"ID-2017-251350410-02", "ID-2017-251350410-03", "ID-2017-251350410-04", 
"ID-2017-251350410-05", "ID-2017-821940719-01", "ID-2017-821940719-02", 
"ID-2017-821940719-04", "ID-2017-821940719-05"), lon.peeps = c(-79.94033, 
-79.939644, -79.94033, -79.972496, -79.943695, -80.086655, -80.121445, 
-79.97723, -79.97723, -79.97723, -79.97723, -79.80957, -79.87476, 
-80.00684, -79.843285, -79.870735, -79.87476, -80.01211, -80.01211, 
-80.01211, -80.01211, -80.03822, -80.03563, -80.01831, -80.03428, 
-80.050766, -80.08372, -80.033844, -80.05077, -80.05808, -80.017334, 
-79.960304, -79.89812, -79.91075), lat.peeps = c(40.466927, 40.46608, 
40.466927, 40.539185, 40.632324, 40.617886, 40.53121, 40.41782, 
40.41782, 40.41782, 40.41782, 40.342606, 40.457756, 40.41485, 
40.516678, 40.408344, 40.457756, 40.42181, 40.42181, 40.42181, 
40.42181, 40.322727, 40.30318, 40.335667, 40.332478, 40.52523, 
40.510147, 40.53659, 40.525955, 40.52417, 40.452763, 40.3647, 
40.49027, 40.462437), dist.to.npo = c(0.068816677752178, 0, 0.068816677752178, 
0, 6.61776013349735, 8.09968467940675, 6.20329698324171, 0, 0, 
0, 0, 0, 0, 7.56057497046757, 4.39920021825653, 3.4244305270775, 
0, 0, 0, 0, 0, 0.99118026020203, 2.33029798875546, 1.40307671291513, 
0.614613198811747, 2.02268689449004, 0, 3.19731608226913, 2.04881834879685, 
1.6609282543407, 0.930777520722411, 6.16790416094753, 6.12014246495763, 
4.82709929229684), min.y.peeps = c(40.46608, 40.46608, 40.46608, 
40.539185, 40.539185, 40.539185, 40.53121, 40.41782, 40.41782, 
40.41782, 40.41782, 40.342606, 40.408344, 40.408344, 40.408344, 
40.408344, 40.408344, 40.42181, 40.42181, 40.42181, 40.42181, 
40.30318, 40.30318, 40.30318, 40.30318, 40.510147, 40.510147, 
40.510147, 40.510147, 40.510147, 40.3647, 40.3647, 40.3647, 40.3647
), max.y.peeps = c(40.466927, 40.466927, 40.466927, 40.632324, 
40.632324, 40.632324, 40.53121, 40.41782, 40.41782, 40.41782, 
40.41782, 40.342606, 40.516678, 40.516678, 40.516678, 40.516678, 
40.516678, 40.42181, 40.42181, 40.42181, 40.42181, 40.335667, 
40.335667, 40.335667, 40.335667, 40.53659, 40.53659, 40.53659, 
40.53659, 40.53659, 40.49027, 40.49027, 40.49027, 40.49027), 
    min.x.peeps = c(-79.94033, -79.94033, -79.94033, -80.086655, 
    -80.086655, -80.086655, -80.121445, -79.97723, -79.97723, 
    -79.97723, -79.97723, -79.80957, -80.00684, -80.00684, -80.00684, 
    -80.00684, -80.00684, -80.01211, -80.01211, -80.01211, -80.01211, 
    -80.03822, -80.03822, -80.03822, -80.03822, -80.08372, -80.08372, 
    -80.08372, -80.08372, -80.08372, -80.017334, -80.017334, 
    -80.017334, -80.017334), max.x.peeps = c(-79.939644, -79.939644, 
    -79.939644, -79.943695, -79.943695, -79.943695, -80.121445, 
    -79.97723, -79.97723, -79.97723, -79.97723, -79.80957, -79.843285, 
    -79.843285, -79.843285, -79.843285, -79.843285, -80.01211, 
    -80.01211, -80.01211, -80.01211, -80.01831, -80.01831, -80.01831, 
    -80.01831, -80.033844, -80.033844, -80.033844, -80.033844, 
    -80.033844, -79.89812, -79.89812, -79.89812, -79.89812), 
    LOCAL = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
    TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)), row.names = c(NA, -34L
), class = c("tbl_df", "tbl", "data.frame"))
```


```{r, fig.width=10, fig.height=8}
dd <- dd2
# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=4,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y),
      axes=FALSE, xlab="", ylab="" )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5) )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=2,
        col=adjustcolor("firebrick",alpha.f=0.5) )
axis( side=1, at=seq(from=min.x,to=max.x,length.out=10),
      labels=c(0,rep("",8),paste(round(d.x,0),"Miles")),
      col="gray", col.axis="gray", cex=1.5)
axis( side=2, at=seq(from=min.y,to=max.y,length.out=10),
      labels=c(0,rep("",8),paste(round(d.y,0),"Miles")),
      col="gray", col.axis="gray", cex=1.5 )
```




```{r, fig.width=10, fig.height=8}
dd <- dd2
# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=4,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y) ) #,
      # axes=FALSE, xlab="", ylab="" )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5) )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=2,
        col=adjustcolor("firebrick",alpha.f=0.5) )
# axis( side=1, at=seq(from=min.x,to=max.x,length.out=10),
#       labels=c(0,rep("",8),paste(round(d.x,0),"Miles")), 
#       col="gray", col.axis="gray", cex=1.5)
# axis( side=2, at=seq(from=min.y,to=max.y,length.out=10),
#       labels=c(0,rep("",8),paste(round(d.y,0),"Miles")), 
#       col="gray", col.axis="gray", cex=1.5 )

text( dd$lon.npo, dd$lat.npo, dd$id.npo )
```

```{r, fig.width=10, fig.height=8}
 # [1] "ID-2015-272357477" "ID-2015-463279966" "ID-2015-471155801" "ID-2015-472085945"
 # [5] "ID-2016-364841262" "ID-2016-421636657" "ID-2016-811470948" "ID-2016-812329206"
 # [9] "ID-2017-251350410" "ID-2017-821940719"



move_node <- function( dd, id, plus.x, plus.y )
{
  these <- dd$id.npo == id
  dd$lon.npo[ these ] <- dd$lon.npo[ these ] + plus.x
  dd$lat.npo[ these ] <- dd$lat.npo[ these ] + plus.y
  dd$lon.peeps[ these ] <- dd$lon.peeps[ these ] + plus.x
  dd$lat.peeps[ these ] <- dd$lat.peeps[ these ] + plus.y 
  return( dd )
}

ddx <- dd

dd <- dd2
# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

dd <- dd[ dd$id.npo != "ID-2015-471155801" , ]
dd <- move_node( dd, "ID-2017-251350410", plus.x=-0.1,  plus.y=-0.1 )
dd <- move_node( dd, "ID-2017-821940719", plus.x=-0.2,  plus.y=0.1  )
dd <- move_node( dd, "ID-2016-811470948", plus.x=-0.05, plus.y=0    )
dd <- move_node( dd, "ID-2015-472085945", plus.x=0,     plus.y=-0.05    )
dd <- move_node( dd, "ID-2015-272357477", plus.x=0,     plus.y=0.02    )


dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=4,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y) ) #,
      # axes=FALSE, xlab="", ylab="" )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5) )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=2,
        col=adjustcolor("firebrick",alpha.f=0.5) )
text( dd$lon.npo, dd$lat.npo, dd$id.npo )
```




```{r, fig.width=10, fig.height=10}
dd <- dd2

# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

# remove overlays 
dd <- dd[ dd$id.npo != "ID-2015-471155801" , ]
dd <- move_node( dd, "ID-2017-251350410", plus.x=-0.1,  plus.y=-0.1 )
dd <- move_node( dd, "ID-2017-821940719", plus.x=-0.2,  plus.y=0.1  )
dd <- move_node( dd, "ID-2016-811470948", plus.x=-0.05, plus.y=0    )
dd <- move_node( dd, "ID-2015-472085945", plus.x=0,     plus.y=-0.05    )
dd <- move_node( dd, "ID-2015-272357477", plus.x=0,     plus.y=0.02    )

par( mar=c(5.1, 4.1, 4.1, 2.1) )
dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=8,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y),
      axes=FALSE, xlab="", ylab="", bg=NULL )
abline( v=seq(from=min.x,to=max.x,length.out=10), col="gray80", lty=2 )
abline( h=seq(from=min.y,to=max.y,length.out=10), col="gray80", lty=2 )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5), lwd=3 )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=3,
        col=adjustcolor("firebrick",alpha.f=0.5) )
axis( side=1, at=seq(from=min.x,to=max.x,length.out=10),
      labels=c(0,rep("",8),paste(round(d.x,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )
axis( side=2, at=seq(from=min.y,to=max.y,length.out=10),
      labels=c(0,rep("",8),paste(round(d.y,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )

```




```{r, fig.width=10, fig.height=10}
dd <- dd2

# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

 # [1] "ID-2015-272357477" "ID-2015-463279966" "ID-2015-471155801" "ID-2015-472085945"
 # [5] "ID-2016-364841262" "ID-2016-421636657" "ID-2016-811470948" "ID-2016-812329206"
 # [9] "ID-2017-251350410" "ID-2017-821940719"

# remove overlays 
dd <- dd[ dd$id.npo != "ID-2015-471155801" , ]
dd <- dd[ dd$id.npo %in% c("ID-2016-811470948",
                         "ID-2015-472085945",
                         "ID-2015-272357477",
                         "ID-2016-364841262") , ]
dd <- move_node( dd, "ID-2017-251350410", plus.x=-0.1,  plus.y=-0.1 )
dd <- move_node( dd, "ID-2017-821940719", plus.x=-0.2,  plus.y=0.1  )
dd <- move_node( dd, "ID-2016-811470948", plus.x=-0.05, plus.y=0    )
dd <- move_node( dd, "ID-2015-472085945", plus.x=0,     plus.y=-0.05    )
dd <- move_node( dd, "ID-2015-272357477", plus.x=0,     plus.y=0.02    )

par( mar=c(5.1, 4.1, 4.1, 2.1) )
dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=8,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y),
      axes=FALSE, xlab="", ylab="", bg=NULL )
abline( v=seq(from=min.x,to=max.x,length.out=10), col="gray80", lty=2 )
abline( h=seq(from=min.y,to=max.y,length.out=10), col="gray80", lty=2 )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5), lwd=3 )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=3,
        col=adjustcolor("firebrick",alpha.f=0.5) )
axis( side=1, at=seq(from=min.x,to=max.x,length.out=10),
      labels=c(0,rep("",8),paste(round(d.x,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )
axis( side=2, at=seq(from=min.y,to=max.y,length.out=10),
      labels=c(0,rep("",8),paste(round(d.y,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )

```


```{r, fig.width=10, fig.height=10}
dd <- dd2

# jitter board members to avoid overplot
dd$lon.peeps <- dd$lon.peeps + rnorm(nrow(dd), 0, 0.005)
dd$lat.peeps <- dd$lat.peeps + rnorm(nrow(dd), 0, 0.005) 

 # [1] "ID-2015-272357477" "ID-2015-463279966" "ID-2015-471155801" "ID-2015-472085945"
 # [5] "ID-2016-364841262" "ID-2016-421636657" "ID-2016-811470948" "ID-2016-812329206"
 # [9] "ID-2017-251350410" "ID-2017-821940719"

# remove overlays 
dd <- dd[ dd$id.npo != "ID-2015-471155801" , ]
dd <- dd[ ! dd$id.npo %in% c("ID-2016-811470948",
                         "ID-2015-472085945",
                         "ID-2015-272357477",
                         "ID-2016-364841262") , ]
dd <- move_node( dd, "ID-2017-251350410", plus.x=-0.1,  plus.y=-0.1 )
dd <- move_node( dd, "ID-2017-821940719", plus.x=-0.2,  plus.y=0.1  )
dd <- move_node( dd, "ID-2016-811470948", plus.x=-0.05, plus.y=0    )
dd <- move_node( dd, "ID-2015-472085945", plus.x=0,     plus.y=-0.05    )
dd <- move_node( dd, "ID-2015-272357477", plus.x=0,     plus.y=0.02    )

par( mar=c(5.1, 4.1, 4.1, 2.1) )
dd3 <- unique( data.frame( lon.npo=dd$lon.npo, lat.npo=dd$lat.npo ) )
plot( dd3$lon.npo, dd3$lat.npo, 
      bty="n", pch=19, col=gray(0.5,0.5), cex=8,
      xlim=c(min.x,max.x), ylim=c(min.y,max.y),
      axes=FALSE, xlab="", ylab="", bg=NULL )
abline( v=seq(from=min.x,to=max.x,length.out=10), col="gray80", lty=2 )
abline( h=seq(from=min.y,to=max.y,length.out=10), col="gray80", lty=2 )
segments( x0=dd$lon.npo, x1=dd$lon.peeps, y0=dd$lat.npo, y1=dd$lat.peeps,
          col=gray(0.5,0.5), lwd=3 )
points( dd$lon.peeps, dd$lat.peeps,pch=19, cex=3,
        col=adjustcolor("firebrick",alpha.f=0.5) )
axis( side=1, at=seq(from=min.x,to=max.x,length.out=10),
      labels=c(0,rep("",8),paste(round(d.x,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )
axis( side=2, at=seq(from=min.y,to=max.y,length.out=10),
      labels=c(0,rep("",8),paste(round(d.y,0),"Miles")),
      col="gray30", col.axis="gray30", cex.axis=1.5 )

```


